server:
  port: 9091

logging:
  config: classpath:config/logback.xml

spring:
  application:
    name: app-order

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      key01: '{cipher}0c46d163a27781944f86487ac29ff7bf1ccf186a216f6e3d5750ed1fc48a773d' #加密字符串加'{cipher}' 例如：'{cipher}加密串'
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true #开启Feign Hystrix 支持

# springboot的Actuator提供了运行状态监控的功能，可以通过REST、远程Shell和JMX方式来查看。
# 这个配置非常重要，否则会导致/actuator/hystrix.stream无法访问,hystrix.stream节点会持续提供熔断状态
management:
  endpoints:
    web:
      #      2.0之前默认是/   2.0默认是 /actuator
      #      base-path: /actuator
      #      显示健康具体信息  默认不会显示详细信息
      #      management.endpoint.health.show-details=always
      exposure:
        include: hystrix.stream # 默认开启health、info，可以通过/actuator/info访问,如果要暴露所有接口,填"*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"