server:
  port: 9092

logging:
  config: classpath:config/logback.xml

spring:
  application:
    name: app-user

eureka:
  client:
    service-url:
      #注册中心地址
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true